_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: true
