_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  content_api: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  shortcut: 0
  single_content_sync: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  weather_blocks: 0
  weather_data: 0
  views: 10
  minimal: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  hello_world: 0
profile: minimal
