_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: -38
    expanded: false
    enabled: false
